---
- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: true
 
- name: Upgrade installed packages
  ansible.builtin.apt:
    upgrade: dist
 
- name: Install common packages
  ansible.builtin.apt:
    name:
      - git
      - curl
      - unzip
      - vim
      - python3-pip
    state: present
