[web]
web-server ansible_host=<WEB_SERVER_PUBLIC_IP>

[web:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=../terraform/generated/generated-key.pem
ansible_python_interpreter=/usr/bin/python3
db_private_ip=<DB_SERVER_PRIVATE_IP>

[database]
db-server ansible_host=<DB_SERVER_PRIVATE_IP> db_private_ip=<DB_SERVER_PRIVATE_IP>

[database:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-A -o ProxyJump=ubuntu@<WEB_SERVER_PUBLIC_IP>'